Use user and group variables in debian SPECS

diff --git a/debs/SPECS/5.0.0/wazuh-agent/debian/postinst b/debs/SPECS/5.0.0/wazuh-agent/debian/postinst
--- a/debs/SPECS/5.0.0/wazuh-agent/debian/postinst
+++ b/debs/SPECS/5.0.0/wazuh-agent/debian/postinst
@@ -1,23 +1,20 @@
 #!/bin/sh
-# postinst script for wazuh-agent
+# postinst script for Wazuh
 # Wazuh, Inc 2015-2020
-
 set -e
-
 case "$1" in
     configure)
 
     OS=$(lsb_release -si)
     VER=$(lsb_release -sr)
     DIR="/var/ossec"
-    USER="ossec"
-    GROUP="ossec"
+    USER="wazuh"
+    GROUP="wazuh"
     WAZUH_GLOBAL_TMP_DIR="${DIR}/packages_files"
-    WAZUH_TMP_DIR="${WAZUH_GLOBAL_TMP_DIR}/agent_config_files"
-    SCRIPTS_DIR="${WAZUH_GLOBAL_TMP_DIR}/agent_installation_scripts"
-    SCA_BASE_DIR="${SCRIPTS_DIR}/sca"
-
+    WAZUH_TMP_DIR="${WAZUH_GLOBAL_TMP_DIR}/manager_config_files"
     OSMYSHELL="/sbin/nologin"
+    SCRIPTS_DIR="${WAZUH_GLOBAL_TMP_DIR}/manager_installation_scripts"
+    SCA_BASE_DIR="${SCRIPTS_DIR}/sca"
 
     if [ ! -f ${OSMYSHELL} ]; then
         if [ -f "/bin/false" ]; then
@@ -25,22 +22,75 @@ case "$1" in
         fi
     fi
 
-    if ! getent group | grep -q "^ossec" ; then
-        addgroup --system ossec > /dev/null 2>&1
+    if ! getent group | grep -q "^wazuh" ; then
+        addgroup --system wazuh  > /dev/null 2>&1
     fi
-    if ! getent passwd | grep -q "^ossec" ; then
+    if ! getent passwd | grep -q "^wazuh" ; then
         adduser --system --home ${DIR} --shell ${OSMYSHELL} --ingroup ${GROUP} ${USER} > /dev/null 2>&1
     fi
 
     if [ -z "$2" ] || [ -f ${WAZUH_TMP_DIR}/create_conf ] ; then
 
-        ${SCRIPTS_DIR}/gen_ossec.sh conf agent ${OS} ${VER} > ${DIR}/etc/ossec.conf
+        ${SCRIPTS_DIR}/gen_ossec.sh conf manager ${OS} ${VER} > ${DIR}/etc/ossec.conf
         ${SCRIPTS_DIR}/add_localfiles.sh >> ${DIR}/etc/ossec.conf
 
+        passlist="${DIR}/agentless/.passlist"
+
+        if [ -f $passlist ] && ! base64 -d $passlist > /dev/null 2>&1; then
+            cp $passlist $passlist.bak
+            base64 $passlist.bak > $passlist
+            if [ $? = 0 ]; then
+                rm -f $passlist.bak
+            else
+                echo "ERROR: Couldn't encode Agentless passlist."
+                mv $passlist.bak $passlist
+            fi
+        fi
     else
-        ${SCRIPTS_DIR}/gen_ossec.sh conf agent ${OS} ${VER} > ${DIR}/etc/ossec.conf.new
+        ${SCRIPTS_DIR}/gen_ossec.sh conf manager ${OS} ${VER} > ${DIR}/etc/ossec.conf.new
         chmod 660 ${DIR}/etc/ossec.conf.new
     fi
+
+    # Remove/relocate existing SQLite databases
+    rm -f ${DIR}/var/db/cluster.db* || true
+    rm -f ${DIR}/var/db/.profile.db* || true
+    rm -f ${DIR}/var/db/agents/* || true
+
+    if [ -f ${DIR}/var/db/global.db ]; then
+        mv ${DIR}/var/db/global.db ${DIR}/queue/db/
+        rm -f ${DIR}/var/db/global.db* || true
+        rm -f ${DIR}/var/db/.template.db || true
+    fi
+
+    if [ -f ${DIR}/queue/db/global.db ]; then
+        chmod 640 ${DIR}/queue/db/global.db*
+        chown ${USER}:${GROUP} ${DIR}/queue/db/global.db*
+    fi
+
+    # Delete uncompatible DBs versions
+    if [ ! -z $2 ]; then
+
+        PREVIOUS_VERSION=$(echo $2 | cut -d"-" -f1)
+
+        # Get the major and minor version
+        MAJOR=$(echo $PREVIOUS_VERSION | cut -d. -f1)
+        MINOR=$(echo $PREVIOUS_VERSION | cut -d. -f2)
+
+        if [ $MAJOR = 3 ] && [ $MINOR -lt 7 ]; then
+            rm -f ${DIR}/queue/db/*.db*
+            rm -f ${DIR}/queue/db/.template.db
+        fi
+    fi
+
+    # Remove Vuln-detector database
+    rm -f ${DIR}/queue/vulnerabilities/cve.db || true
+
+    # Generation auto-signed certificate if not exists
+    if type openssl >/dev/null 2>&1 && [ ! -f "${DIR}/etc/sslmanager.key" ] && [ ! -f "${DIR}/etc/sslmanager.cert" ]; then
+        openssl req -x509 -batch -nodes -days 365 -newkey rsa:2048 -subj "/C=US/ST=California/CN=Wazuh/" -keyout ${DIR}/etc/sslmanager.key -out ${DIR}/etc/sslmanager.cert 2>/dev/null
+    fi
+
+    chmod 640 ${DIR}/etc/sslmanager.cert ${DIR}/etc/sslmanager.key > /dev/null 2>&1 || true
 
     # For the etc dir
     if [ -f /etc/localtime ]; then
@@ -49,17 +99,76 @@ case "$1" in
         chown root:${GROUP} ${DIR}/etc/localtime
     fi
 
-    # Restore the local rules, client.keys and local_decoder
+    if [ -f /etc/TIMEZONE ]; then
+        cp -p /etc/TIMEZONE ${DIR}/etc/;
+        chmod 640 ${DIR}/etc/TIMEZONE
+        chown root:${GROUP} ${DIR}/etc/localtime
+    fi
+
+    # Restore client.keys configuration
     if [ -f ${WAZUH_TMP_DIR}/client.keys ]; then
-        cp ${WAZUH_TMP_DIR}/client.keys ${DIR}/etc/client.keys
+        mv ${WAZUH_TMP_DIR}/client.keys ${DIR}/etc/client.keys
+    fi
+    # Restore local insternal options configuration
+    if [ -f ${WAZUH_TMP_DIR}/local_internal_options.conf ]; then
+        mv ${WAZUH_TMP_DIR}/local_internal_options.conf ${DIR}/etc/local_internal_options.conf
+    fi
+    # Restore lists
+    if [ -d ${WAZUH_TMP_DIR}/lists ]; then
+        cp -rp ${WAZUH_TMP_DIR}/lists  ${DIR}/etc/
     fi
     # Restore ossec.conf configuration
     if [ -f ${WAZUH_TMP_DIR}/ossec.conf ]; then
         mv ${WAZUH_TMP_DIR}/ossec.conf ${DIR}/etc/ossec.conf
     fi
-    # Restore internal options configuration
-    if [ -f ${WAZUH_TMP_DIR}/local_internal_options.conf ]; then
-        mv ${WAZUH_TMP_DIR}/local_internal_options.conf ${DIR}/etc/local_internal_options.conf
+    # Restore local_rules.xml configuration
+    if [ -f ${WAZUH_TMP_DIR}/local_rules.xml ]; then
+        mv ${WAZUH_TMP_DIR}/local_rules.xml ${DIR}/etc/rules/local_rules.xml
+    fi
+    # Restore local_decoders.xml configuration
+    if [ -f ${WAZUH_TMP_DIR}/local_decoder.xml ]; then
+        mv ${WAZUH_TMP_DIR}/local_decoder.xml ${DIR}/etc/decoders/local_decoder.xml
+    fi
+
+    # Restore group files
+    if [ -d ${WAZUH_TMP_DIR}/group ]; then
+        cp -rfp ${WAZUH_TMP_DIR}/group/* ${DIR}/etc/shared
+        rm -rf ${WAZUH_TMP_DIR}/group/
+    fi
+
+    # Restore RBAC database
+    if [ -f ${WAZUH_TMP_DIR}/rbac.db ]; then
+        cp -fp ${WAZUH_TMP_DIR}/rbac.db ${DIR}/api/configuration/security/rbac.db
+        rm -rf ${WAZUH_TMP_DIR}/rbac.db
+    fi
+
+    # Restore API configuration file
+    if [ -f ${WAZUH_TMP_DIR}/api.yaml ]; then
+        cp -fp ${WAZUH_TMP_DIR}/api.yaml ${DIR}/api/configuration/api.yaml
+        rm -rf ${WAZUH_TMP_DIR}/api.yaml
+    fi
+
+    # More files
+    touch ${DIR}/etc/client.keys
+
+    touch ${DIR}/logs/active-responses.log
+    touch ${DIR}/logs/integrations.log
+    chown ${USER}:${GROUP} ${DIR}/logs/active-responses.log
+    chown ${USER}:${GROUP} ${DIR}/logs/integrations.log
+    chmod 0660 ${DIR}/logs/active-responses.log
+    chmod 0640 ${DIR}/logs/integrations.log
+
+
+    if [ -f ${DIR}/etc/shared/ar.conf ]; then
+        chown root:wazuh ${DIR}/etc/shared/ar.conf
+    fi
+
+    # Check if SELinux is installed and enabled
+    if command -v getenforce > /dev/null 2>&1 && command -v semodule > /dev/null 2>&1; then
+        if [ $(getenforce) !=  "Disabled" ]; then
+            semodule -i ${DIR}/var/selinux/wazuh.pp
+            semodule -e wazuh
+        fi
     fi
 
     # Install the SCA files
@@ -85,12 +194,19 @@ case "$1" in
 
         SCA_TMP_FILE="${SCA_TMP_DIR}/sca.files"
 
-        if [ -r ${SCA_TMP_FILE} ]; then
+        if [ -r ${SCA_TMP_FILE} ] && [ -r ${SCA_BASE_DIR}/generic/sca.manager.files ]; then
 
             rm -f ${DIR}/ruleset/sca/* || true
 
             for sca_file in $(cat ${SCA_TMP_FILE}); do
                 mv ${SCA_BASE_DIR}/${sca_file} ${DIR}/ruleset/sca
+            done
+
+            for sca_file in $(cat ${SCA_BASE_DIR}/generic/sca.manager.files); do
+                filename=$(basename ${sca_file})
+                if [ -f "${SCA_BASE_DIR}/${sca_file}" ] && [ ! -f "${DIR}/ruleset/sca/${filename}" ]; then
+                    mv ${SCA_BASE_DIR}/${sca_file} ${DIR}/ruleset/sca/${filename}.disabled
+                fi
             done
         fi
 
@@ -102,42 +218,17 @@ case "$1" in
 
     fi
 
-    # Restore group files
-    if [ -d ${WAZUH_TMP_DIR}/group ]; then
-        for file in ${WAZUH_TMP_DIR}/group/* ; do
-            mv ${file} ${DIR}/etc/shared/
-        done
-        rm -rf ${WAZUH_TMP_DIR}/group
-    fi
-
-    touch ${DIR}/logs/active-responses.log
-    chown wazuh:wazuh ${DIR}/logs/active-responses.log
-    chmod 0660 ${DIR}/logs/active-responses.log
-
-    # Check if SELinux is installed and enabled
-    if command -v getenforce > /dev/null 2>&1 && command -v semodule > /dev/null 2>&1; then
-        if [ $(getenforce) !=  "Disabled" ]; then
-            semodule -i ${DIR}/var/selinux/wazuh.pp
-            semodule -e wazuh
-        fi
-    fi
-
-    # Register and configure agent if Wazuh environment variables are defined
-    if [ -z "$2" ] ; then
-        ${SCRIPTS_DIR}/src/init/register_configure_agent.sh ${DIR} > /dev/null || :
-    fi
-
     # Restoring file permissions
-    ${SCRIPTS_DIR}/restore-permissions.sh > /dev/null 2>&1 || :
+    ${SCRIPTS_DIR}/restore-permissions.sh > /dev/null 2>&1 || true
 
     if [ ! -z "$2" ]; then
         if [ -f ${WAZUH_TMP_DIR}/wazuh.restart ] ; then
-            if command -v systemctl > /dev/null 2>&1 && systemctl > /dev/null 2>&1; then
-                systemctl restart wazuh-agent.service > /dev/null 2>&1
-            elif command -v service > /dev/null 2>&1 ; then
-                service wazuh-agent restart > /dev/null 2>&1
+            if command -v systemctl > /dev/null 2>&1 && systemctl > /dev/null 2>&1 && systemctl is-active --quiet wazuh-manager > /dev/null 2>&1; then
+                systemctl restart wazuh-manager.service > /dev/null 2>&1
+            elif command -v service > /dev/null 2>&1 && service wazuh-manager status 2>/dev/null | grep "running" > /dev/null 2>&1; then
+                service wazuh-manager restart > /dev/null 2>&1
             else
-                ${DIR}/bin/wazuh-control restart > /dev/null 2>&1
+                ${DIR}/bin/wazuh-control restart /dev/null 2>&1
             fi
         fi
     fi
@@ -154,7 +245,7 @@ case "$1" in
 
     # Delete tmp directory
     if [ -d ${WAZUH_TMP_DIR} ]; then
-        rm -rf ${WAZUH_TMP_DIR}
+        rm -r ${WAZUH_TMP_DIR}
     fi
 
     # If the parent directory is empty, delete it
@@ -166,20 +257,20 @@ case "$1" in
     if ! getent group | grep -q "^ossec" ; then
         find ${DIR} -group ossec -user root -exec chown root:wazuh {} \; > /dev/null 2>&1 || true
         if ! getent passwd | grep -q "^ossec" ; then
-            find ${DIR} -group ossec -user ossec -exec chown wazuh:wazuh {} \; > /dev/null 2>&1 || true
+            find ${DIR} -group ossec -user ossec -exec chown ${USER}:${GROUP} {} \; > /dev/null 2>&1 || true
             deluser ossec
         fi
         if ! getent passwd | grep -q "^ossecm" ; then
-            find ${DIR} -group ossec -user ossecm -exec chown wazuh:wazuh {} \; > /dev/null 2>&1 || true
+            find ${DIR} -group ossec -user ossecm -exec chown ${USER}:${GROUP} {} \; > /dev/null 2>&1 || true
             deluser ossecm
         fi
         if ! getent passwd | grep -q "^ossecr" ; then
-            find ${DIR} -group ossec -user ossecr -exec chown wazuh:wazuh {} \; > /dev/null 2>&1 || true
+            find ${DIR} -group ossec -user ossecr -exec chown ${USER}:${GROUP} {} \; > /dev/null 2>&1 || true
             deluser ossecr
         fi
         delgroup ossec 
     fi
-
+    
     ;;
 
 
